### ISSUE TITLE
Eos Node got crashed during replaying process

### ISSUE THREAD

**Issue by yurakocyuba** [EOSLaoMao/elasticsearch_plugin#14]
Hi! 
During replaying eosnode was shutdowned and then I couldn't start it since I got error - database diry flag set and etc. How to understand what happened ?

warn  2018-12-01T12:22:33.692 thread-11 elasticsearch_plugin.c:1025   check_task_queue_siz ] thread pool task queue size: 16499
error 2018-12-01T12:22:33.930 thread-5  exceptions.hpp:34             handle_elasticsearch ] elasticsearch exception, bulk exception, line 26, 3230005 response_code_exception: Get non 2XX response code from Elasticsearch
100 
    {"code":100,"text":""}
    thread-5  elastic_client.cpp:117 bulk_perform
warn  2018-12-01T12:22:34.684 thread-0  elasticsearch_plugin.c:279    queue                ] queue size: 1082
info  2018-12-01T12:22:34.843 thread-11 elasticsearch_plugin.c:1084   consume_blocks       ] process_applied_transaction,  time per: 302148, size: 219, time: 66170630
info  2018-12-01T12:22:35.809 thread-0  net_plugin.cpp:3049           plugin_shutdown      ] shutdown..
info  2018-12-01T12:22:35.809 thread-0  net_plugin.cpp:3052           plugin_shutdown      ] close acceptor
info  2018-12-01T12:22:35.809 thread-0  net_plugin.cpp:3055           plugin_shutdown      ] close 104 connections
error 2018-12-01T12:22:35.816 thread-0  net_plugin.cpp:1373           request_next_chunk   ] Unable to continue syncing at this time
info  2018-12-01T12:22:35.816 thread-0  net_plugin.cpp:3063           plugin_shutdown      ] exit shutdown
info  2018-12-01T12:22:35.816 thread-0  elasticsearch_plugin.c:259    ~elasticsearch_plugi ] elasticsearch_plugin shutdown in process please be patient this can take a few minutes
info  2018-12-01T12:22:40.157 thread-11 elasticsearch_plugin.c:1084   consume_blocks       ] process_applied_transaction,  time per: 4911, size: 1082, time: 5314339
info  2018-12-01T12:22:41.388 thread-11 elasticsearch_plugin.c:1070   consume_blocks       ] draining queue, size: 5
info  2018-12-01T12:22:41.388 thread-11 elasticsearch_plugin.c:1070   consume_blocks       ] draining queue, size: 0
info  2018-12-01T12:22:41.388 thread-11 elasticsearch_plugin.c:1132   consume_blocks       ] elasticsearch_plugin consume thread shutdown gracefully
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument

**Comment by eluzgin** [comment]
This is the line of code throwing exception:
EOS_ASSERT(is_2xx(resp.status_code), chain::response_code_exception, "${code} ${text}", ("code", resp.status_code)("text", resp.text)); 

We received response that is not 200. 

Need to look into EOS_ASSERT code. Regardless a hard fail on any such error is making plugin fragile. 
I would rather have to log the error, and continue processing data.

**Comment by WLBF** [comment]
> Hi!
> During replaying eosnode was shutdowned and then I couldn't start it since I got error - database diry flag set and etc. How to understand what happened ?
> 
> warn 2018-12-01T12:22:33.692 thread-11 elasticsearch_plugin.c:1025 check_task_queue_siz ] thread pool task queue size: 16499
> error 2018-12-01T12:22:33.930 thread-5 exceptions.hpp:34 handle_elasticsearch ] elasticsearch exception, bulk exception, line 26, 3230005 response_code_exception: Get non 2XX response code from Elasticsearch
> 100
> {"code":100,"text":""}
> thread-5 elastic_client.cpp:117 bulk_perform
> warn 2018-12-01T12:22:34.684 thread-0 elasticsearch_plugin.c:279 queue ] queue size: 1082
> info 2018-12-01T12:22:34.843 thread-11 elasticsearch_plugin.c:1084 consume_blocks ] process_applied_transaction, time per: 302148, size: 219, time: 66170630
> info 2018-12-01T12:22:35.809 thread-0 net_plugin.cpp:3049 plugin_shutdown ] shutdown..
> info 2018-12-01T12:22:35.809 thread-0 net_plugin.cpp:3052 plugin_shutdown ] close acceptor
> info 2018-12-01T12:22:35.809 thread-0 net_plugin.cpp:3055 plugin_shutdown ] close 104 connections
> error 2018-12-01T12:22:35.816 thread-0 net_plugin.cpp:1373 request_next_chunk ] Unable to continue syncing at this time
> info 2018-12-01T12:22:35.816 thread-0 net_plugin.cpp:3063 plugin_shutdown ] exit shutdown
> info 2018-12-01T12:22:35.816 thread-0 elasticsearch_plugin.c:259 ~elasticsearch_plugi ] elasticsearch_plugin shutdown in process please be patient this can take a few minutes
> info 2018-12-01T12:22:40.157 thread-11 elasticsearch_plugin.c:1084 consume_blocks ] process_applied_transaction, time per: 4911, size: 1082, time: 5314339
> info 2018-12-01T12:22:41.388 thread-11 elasticsearch_plugin.c:1070 consume_blocks ] draining queue, size: 5
> info 2018-12-01T12:22:41.388 thread-11 elasticsearch_plugin.c:1070 consume_blocks ] draining queue, size: 0
> info 2018-12-01T12:22:41.388 thread-11 elasticsearch_plugin.c:1132 consume_blocks ] elasticsearch_plugin consume thread shutdown gracefully
> terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injectorboost::lock_error >'
> what(): boost: mutex lock failed in pthread_mutex_lock: Invalid argument

Mostly, non 2xx status code is caused by insufficient index performance of elasticsearch, this kind of error indicate that elasticsearch not be able to handle the request from elasticsearch_plugin, so I think shutdown the program is a correct way to handle it. 

```
'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injectorboost::lock_error >'
what(): boost: mutex lock failed in pthread_mutex_lock: Invalid argument
``` 
this lock exception will cause nodeos graceful shutdown fail, probably caused by  wrong destruct order of some member variable. will fix this asap.

**Comment by yurakocyuba** [comment]
I would ask you add more data in logs, very important to understand what caused to non 200 response from elastic. Is there time for which the elastic should return 200 response?

**Comment by WLBF** [comment]
Under the [elasticlient](https://github.com/EOSLaoMao/elasticlient) is [cpr](https://github.com/whoshuu/cpr). `libcurl` enable the [100-continue](https://curl.haxx.se/mail/lib-2017-07/0013.html) by default. The root cause of the 100 response of elasticlient is not very clear, However in my test run, 100 status code mostly show up when index load of elasticsearch come heavier, like at 2200w block.  elasticlient exception handler will print detial information of execption only if there is some text in response. In 100 status case, there are no extra error text in the response. For now, I am not planning to dig this problem.
