### ISSUE TITLE
Got failed during compilation with eos v1.6.0

### ISSUE THREAD

**Issue by yurakocyuba** [EOSLaoMao/elasticsearch_plugin#16]
Hello!

During compilation eos v1.6.0 I got the following:

[ 97%] Linking CXX executable keosd
[ 97%] Built target keosd
/opt/eos/plugins/elasticsearch_plugin/elasticsearch_plugin.cpp:725:31: error: no member named 'trx' in 'eosio::chain::transaction_metadata'
         const auto& trx = t->trx;
                           ~  ^
4 warnings generated.
[ 97%] Linking CXX executable unit_test
[ 97%] Linking CXX static library libdb_size_api_plugin.a
[ 97%] Built target db_size_api_plugin
1 error generated.
plugins/elasticsearch_plugin/CMakeFiles/elasticsearch_plugin.dir/build.make:62: recipe for target 'plugins/elasticsearch_plugin/CMakeFiles/elasticsearch_plugin.dir/elasticsearch_plugin.cpp.o' failed
make[2]: *** [plugins/elasticsearch_plugin/CMakeFiles/elasticsearch_plugin.dir/elasticsearch_plugin.cpp.o] Error 1
CMakeFiles/Makefile2:5561: recipe for target 'plugins/elasticsearch_plugin/CMakeFiles/elasticsearch_plugin.dir/all' failed
make[1]: *** [plugins/elasticsearch_plugin/CMakeFiles/elasticsearch_plugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by WLBF** [comment]
Updated, see: #17
