### ISSUE TITLE
nodeos 1.7.x

### ISSUE THREAD

**Issue by nikitasobolevsky** [EOSLaoMao/elasticsearch_plugin#20]
Hello.
Do you have plans to support nodeos 1.7.x and nodeos 1.8.x?

**Comment by WLBF** [comment]
yes we have.

**Comment by WLBF** [comment]
[release/1.7.x](https://github.com/EOSLaoMao/elasticsearch_plugin/tree/release/1.7.x)
[release/1.8.x](https://github.com/EOSLaoMao/elasticsearch_plugin/tree/release/1.8.x)
